import {
  RiAddBoxFill,
  RiAlertLine,
  RiArrowRightDownBoxFill,
  RiCashFill,
  RiCheckLine,
  RiCloseLine,
  RiDashboardFill,
  RiFileChartFill,
  RiInformationLine,
  RiLogoutBoxFill,
  RiPieChartFill,
  RiQuestionFill,
  RiSettingsFill,
  RiShakeHandsFill,
  RiSidebarFoldFill,
  RiSidebarFoldLine,
  RiSidebarUnfoldFill,
  RiSidebarUnfoldLine,
} from "@remixicon/react"

export const Icon = {
  AddBox: () => <RiAddBoxFill />,
  ArrowRightDownBox: () => <RiArrowRightDownBoxFill />,
  Cash: () => <RiCashFill />,
  Check: () => <RiCheckLine />,
  Close: () => <RiCloseLine />,
  Dashboard: () => <RiDashboardFill />,
  Exclaimation: () => <RiAlertLine />,
  FileChart: () => <RiFileChartFill />,
  Hands: () => <RiShakeHandsFill />,
  HideSidebar: () => <RiSidebarUnfoldFill />,
  Info: () => <RiInformationLine />,
  Logout: () => <RiLogoutBoxFill />,
  Pie: () => <RiPieChartFill />,
  Question: () => <RiQuestionFill />,
  Settings: () => <RiSettingsFill />,
  ShowSidebar: () => <RiSidebarFoldFill />,
}
